# debug: true
spring:
  application:
    name: boot3-logging-sandbox
logging:
  # LoggingApplicationListener で設定をしている。
  level:
    root: DEBUG
    epsilongtmyon:
      app:
        endpoint:
          sandbox01: INFO
  file:
    name: "./log/my.log"
  logback:
    rollingpolicy:
      file-name-pattern: "./log/my.log-%d{yyyy-MM-dd-HH-mm}-%i"
      # max-historyはファイルの数じゃなくて世代の数
      max-history: 3
      # このサイズを超えると%iの部分が増えていく
      max-file-size: 20KB
      clean-history-on-start: false
  structured:
    # 構造化ログについて
    format:
      console: ecs
  # その他、パッケージをグループして、グループ単位でログレベル閾値を設定できる。
