insert into EMP (EMP_ID ,FIRST_NAME ,FAMILY_NAME ,CREATED_AT ,UPDATED_AT)
 values ('EM00001', '一郎', '田中', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into EMP (EMP_ID ,FIRST_NAME ,FAMILY_NAME ,CREATED_AT ,UPDATED_AT)
 values ('EM00002', '二郎', '山本', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
