spring:
  application:
    name: keycloak-oidc-sandbox
  security:
    oauth2:
      # OAuth2ClientProperties
      client:
        registration:
          my-keycloak:
            # とりあえず..
            provider: my-keycloak-provider
            client-id: my-client
            # 検証用keycloakのやつなのでハードコーディングしている。
            client-secret: mMjcupuP0ewSv9c7i8QU20l5nBMEmcKF
            authorization-grant-type: authorization_code
            #redirectUri: http://localhost:8080/home
            scope: openid,profile
        provider:
          my-keycloak-provider:
            # ここから(正確にはこれに続くパス)認可サーバーの各種エンドポイントの場所を取得している。
            issuer-uri: http://localhost:20080/realms/myrealm

