/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.sandbox01;

import org.junit.jupiter.api.Test;

class MainTest {
	@Test
	void appHasAGreeting() {
		Main classUnderTest = new Main();
	}
}
